#ifndef BATTLE_H
#define BATTLE_H

#include "raylib.h"
#include "mech.h"

// ============ FORMULAS (design doc section 4) ============
// Pure functions shared by the battle and the debug screen, so what the debug
// screen prints is exactly what combat uses.
#define HIT_CHANCE_MIN 0.05f
#define HIT_CHANCE_MAX 0.95f
#define ARMORED_THRESHOLD 50        // "targets with > 50 Armor"

float formulaAccuracyMod(float accuracy);     // Accuracy / 100
float formulaEvasionMod(float mobility);      // 1 - Mobility / 200
float formulaHitChance(float weaponAcc, float accuracy, float mobility);   // clamped 5-95%
float formulaScrambleResist(float stability, float strength);   // Stab / (Stab + Strength)

// Every intermediate number of one attack (doc 4.7), for combat and for the debug screen
typedef struct {
    // step 1 - hit chance
    float weaponAcc, accMod, evasionMod, hitUnclamped, spoofMod, hitChance;
    // steps 3-4 - damage
    float baseDamage, power, raw, damageMod, modified;
    // step 5 - armor / integrity split
    float pen;              // weapon pen + chip bonus
    float breachMod;        // Armor Breach Routine multiplier on armor damage
    float toArmor;          // raw * (1 - pen) * breach
    float toIntegrity;      // raw * pen
    int armorBefore;
    int armorDamage;        // absorbed by armor
    int spill;              // armor damage beyond current armor
    int integrityDamage;    // toIntegrity + spill
    // extras
    int heat;               // heat generated by the shot
    int scramble;
    float resist;           // target's chance to resist the scramble
} AttackPreview;

// Per-attack conditions that come from battle state rather than stats
typedef struct {
    float attackerAccuracy;     // effective (scramble penalties / precision strike applied)
    float targetMobility;       // effective (evasive maneuver / emergency evasion applied)
    int targetArmor;            // current armor
    int spoofActive;            // target's Targeting Spoof applies to this attack
    int breachReady;            // attacker's Armor Breach Routine still unused vs this target
} AttackContext;

void attackPreview(const Stats* atk, const Firmware* atkFw, const WeaponDef* w,
                   const Stats* def, const Firmware* defFw, const AttackContext* ctx, AttackPreview* out);
AttackContext attackContextBaseline(const Stats* atk, const Firmware* atkFw,
                                    const Stats* def, const Firmware* defFw, int targetArmor);
float hackChance(const Mech* target, const Stats* targetStats);
int revisionDataForWild(const Mech* enemy);
int revisionDataForTrainer(const Mech* enemy, int tier);

// ============ BATTLE STATE ============
typedef enum {
    BP_PLAYER_TURN,
    BP_ENEMY_TURN,
    BP_VICTORY,     // enemy scrapped or hacked, waiting for confirm
    BP_DEFEAT,      // player's mech disabled, waiting for confirm
    BP_OVER         // main loop should leave the battle (see battle.result)
} BattlePhase;

typedef enum { DLG_NONE = 0, DLG_INTRO, DLG_DEFEAT } BattleDialogue;
typedef enum { RESULT_NONE, RESULT_TO_WORLD, RESULT_TO_REVISION } BattleResult;

typedef struct {
    Mech* mech;
    Stats stats;            // effective stats at battle start
    int energy, heat;
    int actionsThisTurn;
    int attackedThisRound;  // for Targeting Spoof
    int breachUsed;         // Armor Breach Routine spent
    int lastStandUsed, emergencyPowerUsed;
    int evasiveBonus;       // Mobility until this side's next turn
    // scramble effects active this turn
    int accPenalty, disabledWeapon, skipTurn;
    // scramble effects queued for this side's next turn
    int nextEnergyLoss, nextAccPenalty, nextDisabledWeapon, nextSkipTurn;
} Combatant;

// A visual/audio cue for ui_battle.c; battle logic never touches effects directly
typedef struct { int fx; int fromPlayer; int damage; int hit; Color color; } BattleEvent;
#define MAX_BATTLE_EVENTS 8

typedef struct {
    BattlePhase phase;
    BattleDialogue dialogue;
    char dialogueText[256];
    char log[256];
    Combatant player, enemy;
    Mech enemyMech;
    int trainer;            // -1 = wild
    int round;
    float animTimer;        // > 0 while an attack animation plays
    int outcomePending;     // check for scrapped mechs once the animation ends
    int dataEarned, revisionsGained, oldRevision, hacked;
    BattleResult result;
    BattleEvent events[MAX_BATTLE_EVENTS];
    int numEvents;
} Battle;

extern Battle battle;

void battleStartWild(void);
void battleStartTrainer(int trainerIdx);
void battleUpdate(float dt);
int battleBusy(void);                       // animating or showing dialogue
int battleCanFire(int mount, const char** reason);
void battleFire(int mount);
void battleEndTurn(void);
int battleCanHack(void);
void battleHack(void);
void battleConfirm(void);                   // advance dialogue / victory / defeat
int battlePopEvent(BattleEvent* out);
int battlePreviewPlayer(int mount, AttackPreview* out);   // live numbers for a player weapon, 0 if empty
float combatMobility(const Combatant* c);   // effective values used for attacks
float combatAccuracy(const Combatant* c);

#endif
