#include "firmware.h"

// Algorithmic Chips (design doc 7.7 - 7.9). Only chips whose effect the battle
// already understands are listed; add a ChipEffect before adding new behaviours.
const ChipDef chipDefs[NUM_CHIPS] = {
    //  name                            category       rarity               cost effect                  stat             value
    { "PREDICTIVE TARGETING",           CAT_PASSIVE,   RARITY_STANDARD,     1, CFX_STAT,                STAT_ACCURACY,   5,
      "+5 Accuracy." },
    { "HARDENED KERNEL",                CAT_PASSIVE,   RARITY_STANDARD,     1, CFX_STAT,                STAT_STABILITY,  10,
      "+10 Stability." },
    { "THERMAL OPTIMIZATION",           CAT_PASSIVE,   RARITY_STANDARD,     2, CFX_ENERGY_HEAT_CUT,     STAT_HEAT,       0.10f,
      "-10% Heat generated by Energy weapons." },
    { "EFFICIENT POWER DISTRIBUTION",   CAT_PASSIVE,   RARITY_ADVANCED,     4, CFX_FIRST_ACTION_FREE,   STAT_ENERGY,     1,
      "The first action each turn costs 0 Energy." },
    { "ARMOR ANALYSIS",                 CAT_OFFENSIVE, RARITY_STANDARD,     2, CFX_PEN_VS_ARMORED,      STAT_POWER,      0.20f,
      "+20% Armor Penetration vs targets with > 50 Armor." },
    { "ARMOR BREACH ROUTINE",           CAT_OFFENSIVE, RARITY_ADVANCED,     2, CFX_ARMOR_BREACH,        STAT_ARMOR,      0.25f,
      "First attack vs an armored enemy deals +25% Armor damage." },
    { "PRECISION STRIKE",               CAT_OFFENSIVE, RARITY_STANDARD,     2, CFX_PRECISION_STRIKE,    STAT_ACCURACY,   20,
      "First attack each turn gains +20 Accuracy." },
    { "EMERGENCY EVASION PROTOCOL",     CAT_MOBILITY,  RARITY_STANDARD,     2, CFX_EMERGENCY_EVASION,   STAT_MOBILITY,   30,
      "Below 25% Integrity: +30 Mobility." },
    { "EVASIVE MANEUVER",               CAT_MOBILITY,  RARITY_STANDARD,     2, CFX_EVASIVE_MANEUVER,    STAT_MOBILITY,   20,
      "After attacking, +20 Mobility until your next turn." },
    { "EMERGENCY POWER ROUTING",        CAT_DEFENSIVE, RARITY_STANDARD,     2, CFX_EMERGENCY_POWER,     STAT_ENERGY,     1,
      "Once below 25% Integrity: +1 Energy next turn." },
    { "COUNTER-INTRUSION",              CAT_EW,        RARITY_STANDARD,     2, CFX_COUNTER_INTRUSION,   STAT_STABILITY,  25,
      "+25 Stability when resisting Scramble." },
    { "TARGETING SPOOF",                CAT_EW,        RARITY_ADVANCED,     3, CFX_TARGETING_SPOOF,     STAT_ACCURACY,   0.20f,
      "First attack against this robot each round: -20% hit chance." },
    { "SYSTEM RECOVERY",                CAT_TRIGGERED, RARITY_ADVANCED,     2, CFX_SYSTEM_RECOVERY,     STAT_INTEGRITY,  10,
      "Resisting a Scramble restores 10 Integrity." },
    { "LAST STAND",                     CAT_TRIGGERED, RARITY_EXPERIMENTAL, 3, CFX_LAST_STAND,          STAT_ENERGY,     2,
      "First time below 10% Integrity: +2 Energy." },
};
