#include "game.h"
#include "world.h"

// ============ FACTIONS ============
const Faction factions[NUM_FACTIONS] = {
    { "IRON LEGION",      FKIND_CRIMINAL, { 255, 180, 60, 255 },
      "Mercenary cartel running piloted heavy mechs across every sector." },
    { "CHROME SYNDICATE", FKIND_CRIMINAL, { 120, 220, 255, 255 },
      "Smugglers and signal thieves. Fast frames, dirty electronics." },
    { "BLACK BOX",        FKIND_ROGUE_AI, { 200, 60, 255, 255 },
      "Machines that lost their operators and kept fighting. Reprogrammable." },
};

// ============ MANUFACTURERS ============
// One showroom per region: ATLAS in Alpha, KESTREL in Beta, HELIOS in Gamma,
// VANGUARD in Delta (the wider role line-up), BLACKSITE in Omega (rare frames).
const Company companies[NUM_COMPANIES] = {
    { "ATLAS HEAVY INDUSTRIES", "Frontline frames, built to take the hit.", { 255, 170, 90, 255 } },
    { "KESTREL DYNAMICS",       "Recon and electronic warfare, light and fast.", { 120, 230, 255, 255 } },
    { "HELIOS ORDNANCE",        "Long-range artillery platforms.", { 255, 120, 120, 255 } },
    { "VANGUARD SYSTEMS",       "Specialist frames for every role.", { 170, 230, 140, 255 } },
    { "BLACKSITE ARMORY",       "Prototype frames, no questions asked.", { 200, 120, 255, 255 } },
};

const CatalogEntry catalog[NUM_CATALOG] = {
    //  company      chassis        level price
    { CO_ATLAS,   MODEL_NOVA,     1,   350 },
    { CO_ATLAS,   MODEL_BULWARK,  1,   450 },
    { CO_ATLAS,   MODEL_RAZOR,    1,   420 },
    { CO_ATLAS,   MODEL_RAMPART,  2,   600 },
    { CO_KESTREL, MODEL_WISP,     3,   650 },
    { CO_KESTREL, MODEL_HOUND,    3,   600 },
    { CO_KESTREL, MODEL_STATIC,   3,   700 },
    { CO_KESTREL, MODEL_SNARE,    3,   650 },
    { CO_KESTREL, MODEL_HALO,     3,   700 },
    { CO_KESTREL, MODEL_VANTAGE,  3,   650 },
    { CO_HELIOS,  MODEL_LONGBOW,  5,  1150 },
    { CO_HELIOS,  MODEL_HAVOC,    5,  1250 },
    // the role line-up: the plain frames sell next to their class...
    { CO_ATLAS,   MODEL_BRUTE,    1,   380 },
    { CO_ATLAS,   MODEL_CITADEL,  1,   480 },
    { CO_KESTREL, MODEL_DART,     3,   600 },
    { CO_KESTREL, MODEL_PICKET,   3,   620 },
    { CO_KESTREL, MODEL_JOLT,     3,   640 },
    { CO_HELIOS,  MODEL_BALLISTA, 5,  1050 },
    { CO_HELIOS,  MODEL_PELTER,   5,  1000 },
    // ...the specialists in Delta...
    { CO_VANGUARD, MODEL_WRECKER,   6, 1400 },
    { CO_VANGUARD, MODEL_CINDER,    6, 1350 },
    { CO_VANGUARD, MODEL_FORTRESS,  6, 1450 },
    { CO_VANGUARD, MODEL_RHINO,     6, 1400 },
    { CO_VANGUARD, MODEL_REDOUBT,   6, 1450 },
    { CO_VANGUARD, MODEL_GRANITE,   6, 1400 },
    { CO_VANGUARD, MODEL_CATAPULT,  6, 1400 },
    { CO_VANGUARD, MODEL_TEMPEST,   6, 1500 },
    { CO_VANGUARD, MODEL_VULCAN,    6, 1500 },
    { CO_VANGUARD, MODEL_SHADE,     6, 1350 },
    { CO_VANGUARD, MODEL_TALON,     6, 1350 },
    { CO_VANGUARD, MODEL_PROBE,     6, 1350 },
    { CO_VANGUARD, MODEL_STALKER,   6, 1350 },
    { CO_VANGUARD, MODEL_PANTHER,   6, 1300 },
    { CO_VANGUARD, MODEL_RELAY,     6, 1400 },
    { CO_VANGUARD, MODEL_PALLADIUM, 6, 1450 },
    { CO_VANGUARD, MODEL_WARD,      6, 1400 },
    { CO_VANGUARD, MODEL_BRAMBLE,   6, 1450 },
    { CO_VANGUARD, MODEL_THORN,     6, 1450 },
    // ...and the rare ones in Omega
    { CO_BLACKSITE, MODEL_LANCE,    8, 2200 },
    { CO_BLACKSITE, MODEL_REAPER,   8, 2300 },
    { CO_BLACKSITE, MODEL_NEEDLE,   8, 2200 },
    { CO_BLACKSITE, MODEL_WRAITH,   8, 2100 },
    { CO_BLACKSITE, MODEL_NEXUS,    8, 2100 },
    { CO_BLACKSITE, MODEL_SCREAMER, 8, 2000 },
    // wave 2: plain frames by class...
    { CO_ATLAS,   MODEL_MAUL,       1,  420 },
    { CO_ATLAS,   MODEL_ANVIL,      1,  440 },
    { CO_ATLAS,   MODEL_MONOLITH,   1,  500 },
    { CO_KESTREL, MODEL_CUTTER,     3,  620 },
    { CO_KESTREL, MODEL_ZEPHYR,     3,  660 },
    { CO_KESTREL, MODEL_GLITCH,     3,  640 },
    { CO_KESTREL, MODEL_FORERUNNER, 3,  650 },
    { CO_HELIOS,  MODEL_HIVE,       5, 1100 },
    { CO_HELIOS,  MODEL_GATLING,    5, 1150 },
    { CO_HELIOS,  MODEL_STONEFALL,  5, 1250 },
    { CO_HELIOS,  MODEL_KRAKEN,     5, 1300 },
    // ...specialists in Delta...
    { CO_VANGUARD, MODEL_SPLITTER,  6, 1450 },
    { CO_VANGUARD, MODEL_KEEP,      6, 1450 },
    { CO_VANGUARD, MODEL_STAMPEDE,  6, 1400 },
    { CO_VANGUARD, MODEL_PALISADE,  6, 1500 },
    { CO_VANGUARD, MODEL_SENTINEL,  6, 1450 },
    { CO_VANGUARD, MODEL_MAGMA,     6, 1500 },
    { CO_VANGUARD, MODEL_SHATTER,   6, 1450 },
    { CO_VANGUARD, MODEL_VERDICT,   6, 1400 },
    { CO_VANGUARD, MODEL_CASCADE,   6, 1450 },
    { CO_VANGUARD, MODEL_SPECTER,   6, 1450 },
    { CO_VANGUARD, MODEL_VEIL,      6, 1400 },
    { CO_VANGUARD, MODEL_HORIZON,   6, 1400 },
    { CO_VANGUARD, MODEL_LURKER,    6, 1350 },
    { CO_VANGUARD, MODEL_JACKAL,    6, 1300 },
    { CO_VANGUARD, MODEL_BEACON,    6, 1400 },
    { CO_VANGUARD, MODEL_CIPHER,    6, 1400 },
    { CO_VANGUARD, MODEL_CALTRAP,   6, 1450 },
    { CO_VANGUARD, MODEL_HEDGE,     6, 1450 },
    { CO_VANGUARD, MODEL_SHELTER,   6, 1450 },
    // ...and the rare ones in Omega
    { CO_BLACKSITE, MODEL_HAWKEYE,  8, 2200 },
    { CO_BLACKSITE, MODEL_PHANTOM,  8, 2200 },
    { CO_BLACKSITE, MODEL_ORACLE,   8, 2100 },
    { CO_BLACKSITE, MODEL_MIRROR,   8, 2100 },
    { CO_BLACKSITE, MODEL_SANCTUM,  8, 2200 },
};

// ============ JOB BOARD ============
// Posted on the terminal of their region. Bounties name their target encounter,
// so the board survives the encounter list being reordered.
const JobDef jobDefs[NUM_JOBS] = {
    // ---- SECTOR ALPHA ----
    { "PEST CONTROL", "Alpha Relay Co-op", JOB_CULL, REGION_ALPHA, NULL, -1, 3,
      120, REWARD_WEAPON, W_GRENADE_LAUNCHER,
      "Feral machines keep chewing through our relay cables. Scrap three in the Alpha ruins." },
    { "FIELD RECOVERY", "Kestrel Dynamics", JOB_RECOVER, REGION_ALPHA, NULL, -1, 1,
      100, REWARD_CHIP, CHIP_EMERGENCY_EVASION,
      "Reprogram any rogue machine in Sector Alpha. Keep the unit - we only want its telemetry." },
    { "RECRUITER", "Sector Watch", JOB_BOUNTY, REGION_ALPHA, "PILOT RHEA", -1, 1,
      150, REWARD_MODULE, REFIT_TARGETING_ARRAY,
      "Iron Legion pilot Rhea is recruiting in the calibration field. Put her mech down." },
    { "SPEED TRAP", "Sector Watch", JOB_BOUNTY, REGION_ALPHA, "SCOUT DANE", -1, 1,
      150, REWARD_MODULE, REFIT_JUMP_JETS,
      "Scout Dane runs Legion messages between sectors. Intercept him." },
      // ---- SECTOR BETA ----
      { "IRON FIST", "Sector Watch", JOB_BOUNTY, REGION_BETA, "COMMANDER VOLK", -1, 1,
        350, REWARD_MODULE, REFIT_HEAVY_PLATING,
        "Commander Volk holds the industrial ruins for the Legion. Break his line." },
      { "SIGNAL THIEF", "Kestrel Dynamics", JOB_BOUNTY, REGION_BETA, "ENGINEER KESS", -1, 1,
        350, REWARD_CHIP, CHIP_THERMAL_OPTIMIZATION,
        "Syndicate engineer Kess stole our jamming firmware. Shut her workshop down." },
      { "JAMMER SPECIMEN", "Kestrel Dynamics", JOB_RECOVER, REGION_BETA, NULL, ARCH_JAMMER, 1,
        250, REWARD_WEAPON, W_VIRUS_UPLINK,
        "A rogue JAMMER is loose in Beta. Reprogram it intact and we'll share the payload we pull from it." },
      { "SCRAP QUOTA", "Atlas Heavy Industries", JOB_CULL, REGION_BETA, NULL, -1, 4,
        250, REWARD_MECH, MODEL_BULWARK,
        "Clear four rogue machines from our Beta supply route. Payment includes a demo BULWARK." },
        // ---- SECTOR GAMMA ----
        { "WARDEN'S END", "Sector Watch", JOB_BOUNTY, REGION_OMEGA, "WARDEN KRUX", -1, 1,
          700, REWARD_CHIP, CHIP_OVERCHARGE,
          "Warden Krux commands the Legion from the wasteland. End it." },
        { "GHOST HUNT", "Helios Ordnance", JOB_BOUNTY, REGION_GAMMA, "GHOST ECHO", -1, 1,
          700, REWARD_MODULE, REFIT_HOVER_SYSTEM,
          "Ghost Echo has been raiding our test ranges. Find the Syndicate ace and scrap the squad." },
        { "ARTILLERY SURVEY", "Helios Ordnance", JOB_RECOVER, REGION_GAMMA, NULL, ARCH_BOMBARD, 1,
          500, REWARD_WEAPON, W_SIEGE_MORTAR,
          "Reprogram a rogue BOMBARD in Gamma. We want to see what the wasteland did to our design." },
        { "BLACK BOX", "Sector Watch", JOB_BOUNTY, REGION_OMEGA, "FACTORY OVERSEER", -1, 1,
          1500, REWARD_CHIP, CHIP_DEAD_MAN,
          "The Factory Overseer is building an army out of Gamma scrap. Destroy the core." },
};